#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

picom &

xsetroot -cursor_name left_ptr &

nitrogen /usr/share/wallpapers --random --set-zoom-fill &

$HOME/.config/polybar/launch.sh

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Pavucontrol state=floating 
