[mgr]
border_symbol = "│"

[status]
perm_type = { fg = "#3b8eea" }
perm_read = { fg = "#23d18b" }
perm_write = { fg = "#f5f543" }
perm_exec = { fg = "#f14c4c" }
perm_sep = { fg = "#414140" }

[flavor]
dark  = "noctalia"
light = "noctalia"